apiVersion: v2
name: photoprism
description: Photoprism by mmontes11
type: application
version: 0.12.0
appVersion: "251130"
maintainers:
  - name: mmontes11
    email: martin11lrx@gmail.com
keywords:
  - "photoprism"
  - "photos"
  - "media"
  - "google-photos"
  - "ai"
  - "ollama"
